{"uuid": "6e1d793f-5eb6-4d62-ae79-aa07131c3bb8", "children": ["16c1247d-f38e-4998-9623-5ee3535de514"], "befores": [{"name": "driver", "status": "passed", "start": 1724909848903, "stop": 1724909883856}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\pytest_demowebshop\\Tests\\conftest.py\", line 10, in driver\n    driver.quit()\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 146, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 120, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nithya\\Desktop\\python_pom_framework\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Nithya\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 844, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1724909884206, "stop": 1724909886321}], "start": 1724909848903, "stop": 1724909886321}